/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    'IconTabler:brandNuxt': typeof import('~icons/tabler/brand-nuxt')['default']
    IconTablerBrandNuxt: typeof import('~icons/tabler/brand-nuxt')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
